group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Item"
imports_layout = "HorizontalVertical"
max_width = 120
merge_derives = false
newline_style = "Unix"
style_edition = "2024"
use_field_init_shorthand = true
